# Generated by Django 4.2.20 on 2025-05-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blockedip'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRangeCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_start', models.BigIntegerField()),
                ('ip_end', models.BigIntegerField()),
                ('country_code', models.CharField(max_length=2)),
            ],
        ),
    ]
